# Logging Configuration
logging:
  level: INFO
  loggers:
    BankingApplication: DEBUG

# the name of the file where properties are defined
propertyFileName: application

database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: root
  # the JDBC URL; the database is called Banking
  url: jdbc:mysql://localhost:3306/banking